version: '3.4'

networks:
  blue:
    driver: bridge

services:
  mongo:
    image: mongo:4.2
    networks:
      - blue
    environment:
      MONGOLAB_URI: mongodb://localhost:27017/schedule-blue 
    ports:
      - "27017:27017"